"""This module configures text analysis/normalisation in the Elasticsearch index.

For further information see: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis.html
"""

from elasticsearch_dsl import analyzer, token_filter, char_filter

transcript_analyzer = analyzer(
    'transcript_analyzer',
    tokenizer="standard",
    filter=[
        "lowercase",
        token_filter('german_stop', 'stop', stopwords='_german_'),
        token_filter('german_snowball', 'snowball', language='German2'),
    ],
    char_filter=[
        "html_strip",
        char_filter('bracket_strip', 'mapping', mappings=['[ => ', '] => ']),
        char_filter('diacritics', 'mapping', mappings=[
            'á => a',
            'à => a',
            'À => a',
            'ă => a',
            'Ă => a',
            'â => a',
            'Â => a',
            'ǎ => a',
            'Å => a',
            'ã => a',
            'Ã => a',
            'ā => a',
            'ạ => a',
            'ḁ => a',
            'Ḁ => a',
            'Aͤ => ae',
            'æ => ae',
            'Æ => ae',
            'ç => c',
            'Ç => c',
            'é => e',
            'É => e',
            'è => e',
            'È => e',
            'ĕ => e',
            'ê => e',
            'Ê => e',
            'ë => e',
            'Ë => e',
            'ẽ => e',
            'ę => e',
            'ē => e',
            'Ē => e',
            'ẹ => e',
            'Eͣ => ea',
            'ǥ => g',
            'í => i',
            'ì => i',
            'Ì => i',
            'ĭ => i',
            'î => i',
            'Î => i',
            'ï => i',
            'Ï => i',
            'ĩ => i',
            'ī => i',
            'ị => i',
            'iͤ => ie',
            'ı => i',
            'j => j',
            'ñ => n',
            'ó => o',
            'Ó => o',
            'ò => o',
            'Ò => o',
            'ŏ => o',
            'ô => o',
            'Ô => o',
            'ǒ => o',
            'Ǒ => o',
            'ọ̈ => ö',
            'õ => o',
            'Õ => o',
            'ṏ => ö',
            'ø => ö',
            'Ø => ö',
            'ō => o',
            'ȍ => ö',
            'Ȍ => ö',
            'ọ => o',
            'Oͤ => oe',
            'œ => oe',
            'Œ => oe',
            'ṣ => s',
            'ſ => s',
            'ß => ss',
            'ú => u',
            'Ú => u',
            'ù => u',
            'Ù => u',
            'ŭ => u',
            'Ŭ => u',
            'û => u',
            'Û => u',
            'ǔ => u',
            'ů => uo',
            'Ů => uo',
            'Ů => uo',
            'ǜ => ü',
            'ụ̈ => ü',
            'u̇ => u',
            'ū => u',
            'ȕ => ü',
            'Ȕ => ü',
            'ụ => u',
            'Uͤ => ue',
            'V̊ => uo',
            'v̈ => ü',
            'w̆ => w',
            'ẅ => w',
            'y => y',
            'ý => y',
            'ÿ => y',
            'Ÿ => y',
            'ẏ => y',
            'ʒ => z',
            'ε => e',
            'oͤ => oe',
            'uͤ => ue',
            'aͤ => ae',
            'vͥ => ü',
            'uͥ => ü',
            'ü => ue',
            'ö => oe',
            'ä => ae',
        ])
    ]
)