# Generated by Django 3.2 on 2021-04-09 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='illuminated',
        ),
        migrations.RemoveField(
            model_name='document',
            name='submitted_by_anonymous',
        ),
        migrations.AddField(
            model_name='document',
            name='publish_user',
            field=models.BooleanField(default=False, help_text='Select this, if you want to publish this document anonymously', verbose_name='Publish anonymous'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='illuminated',
            field=models.BooleanField(help_text='Does the source contain painted miniatures (=illuminations)?', null=True, verbose_name='Illuminations'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Authors, Copiers, Editors', related_name='works', to='main.Author', verbose_name='Source Participants'),
        ),
        migrations.AlterField(
            model_name='document',
            name='comments',
            field=models.TextField(blank=True, help_text='Add editorial comments or remarks on the contents of the document.', verbose_name='Editorial comments'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_utc_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='material',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), (1, 'Paper'), (2, 'Parchment'), (3, 'Papyrus')], help_text='Is the manuscript on paper, papyrus or parchment?', max_length=15, verbose_name='Writing material'),
        ),
        migrations.AlterField(
            model_name='document',
            name='measurements_length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in centimeters (cm)', max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='document',
            name='measurements_width',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Width in centimeters (cm)', max_digits=5, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The number of pages of the whole source', null=True, verbose_name='Number of pages'),
        ),
        migrations.AlterField(
            model_name='document',
            name='paging_system',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), (1, 'Pagination'), (2, 'Foliated')], help_text='How are the pages numbered?', max_length=15, verbose_name='Pagination'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent_ref_number',
            field=models.ForeignKey(help_text='Signatur der Quelle', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='main.refnumber', verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='document',
            name='place_name',
            field=models.CharField(help_text='The City/Place where the source was created.', max_length=150, verbose_name='Creation Location'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.ForeignKey(help_text='Type of the source', on_delete=django.db.models.deletion.PROTECT, to='main.sourcetype', verbose_name='Source Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='submitted_by',
            field=models.ForeignKey(editable=False, help_text='Uploading user', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by'),
        ),
        migrations.AlterField(
            model_name='document',
            name='transcription_text',
            field=models.TextField(help_text='Formatted text of your transcript.', verbose_name='Transcript'),
        ),
    ]
