# Generated by Django 3.2.7 on 2021-10-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_language',
            field=models.CharField(choices=[('en-us', 'English'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian')], default='en', help_text='What is your preferred language?', max_length=20, verbose_name='Default User Interface Language'),
        ),
    ]
