# Generated by Django 3.2.7 on 2021-10-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('main', '0002_user_ui_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Authors, Copiers, Editors', to='main.Author', verbose_name='Source Participants'),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='Languages used in the source', to='languages_plus.Language', verbose_name='Languages'),
        ),
    ]
