# Generated by Django 3.2 on 2021-04-09 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210409_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='transcription_text',
            field=ckeditor.fields.RichTextField(help_text='Formatted text of your transcript.', verbose_name='Transcript'),
        ),
    ]
