# Generated by Django 3.2 on 2021-04-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_document_transcription_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_utc_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent_ref_number',
            field=models.ForeignKey(help_text='Signatur der Quelle', on_delete=django.db.models.deletion.PROTECT, to='main.refnumber', verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='refnumber',
            name='holding_institution',
            field=models.ForeignKey(help_text='Institution associated with this reference number', on_delete=django.db.models.deletion.PROTECT, to='main.institution', verbose_name='Institution'),
        ),
    ]
