# Generated by Django 3.2.11 on 2022-01-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211015_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetype',
            name='type_name_de',
            field=models.CharField(default='', max_length=50, verbose_name='archivalienart'),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='type_name_fr',
            field=models.CharField(default='', max_length=50, verbose_name='archivalienart'),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='type_name_it',
            field=models.CharField(default='', max_length=50, verbose_name='archivalienart'),
        ),
    ]
