# Generated by Django 3.2 on 2021-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210410_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentPage',
        ),
        migrations.AddField(
            model_name='document',
            name='illuminated',
            field=models.BooleanField(help_text='Does the source contain painted miniatures (=illuminations)?', null=True, verbose_name='Illuminations'),
        ),
        migrations.AddField(
            model_name='document',
            name='seal',
            field=models.BooleanField(help_text='Are there any seals on this page?', null=True, verbose_name='Seal'),
        ),
        migrations.AlterField(
            model_name='document',
            name='material',
            field=models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'Paper'), (2, 'Parchment'), (3, 'Papyrus')], help_text='Is the manuscript on paper, papyrus or parchment?', verbose_name='Writing material'),
        ),
        migrations.AlterField(
            model_name='document',
            name='paging_system',
            field=models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'Pagination'), (2, 'Foliated')], help_text='How are the pages numbered?', verbose_name='Pagination'),
        ),
        migrations.AlterField(
            model_name='document',
            name='transcription_scope',
            field=models.TextField(help_text='List of the transcribed pages/chapters, etc.', verbose_name='Transcribed parts of the document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Enter your email address', max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=True, help_text='Has the user confirmed the email address?', verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Enter your first name(s)', max_length=150, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the user active? Users get deactivated instead of deleted.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Does the user have staff status and can thus login to the admin page?', verbose_name='Staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Enter your last name', max_length=150, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Provide a user name', max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
