# Generated by Django 3.2.11 on 2022-01-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newsletter_newsletterrecipients_newsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipients',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian')], default='en', help_text='What is your preferred language?', max_length=20, verbose_name='Default User Interface Language'),
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='news_message_de',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='news_message_fr',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='news_message_it',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='news_title_de',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='news_title_fr',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='news_title_it',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
