# Generated by Django 3.2 on 2021-04-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210423_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'get_latest_by': 'document_utc_add', 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='illuminated',
            field=models.BooleanField(blank=True, help_text='Does the source contain painted miniatures (=illuminations)?', null=True, verbose_name='Illuminations'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent_institution',
            field=models.ForeignKey(help_text='Institution, welche die Quelle aufbewahrt', on_delete=django.db.models.deletion.PROTECT, to='main.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='document',
            name='seal',
            field=models.BooleanField(blank=True, help_text='Are there any seals on this page?', null=True, verbose_name='Seal'),
        ),
    ]
