# Generated by Django 3.2.11 on 2022-01-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220121_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmessage',
            name='uploading_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
