# Generated by Django 3.2 on 2021-05-24 13:42

from django.db import migrations, models
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210426_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'default_manager_name': 'objects', 'get_latest_by': 'document_utc_add', 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='parent_institution',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_end_date',
            field=partial_date.fields.PartialDateField(blank=True, null=True, verbose_name='Creation period end'),
        ),
        migrations.AlterField(
            model_name='document',
            name='paging_system',
            field=models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'Pagination'), (2, 'Foliated')], help_text='How are the pages numbered?', null=True, verbose_name='Pagination'),
        ),
    ]
