# Generated by Django 3.2.11 on 2022-01-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_newsmessage_uploading_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_name_de', models.CharField(default=None, max_length=50, null=True)),
                ('tag_name_fr', models.CharField(default=None, max_length=50, null=True)),
                ('tag_name_it', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='message_tags',
            field=models.ManyToManyField(to='main.TopicTag'),
        ),
    ]
