# Generated by Django 3.2.3 on 2021-06-01 06:56

from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210524_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(help_text='Complete name of the institution', max_length=80, unique=True, verbose_name='Institution')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_end_date',
            field=partial_date.fields.PartialDateField(blank=True, help_text='If the document was created over a time span, please indicate the end time.', null=True, verbose_name='Creation period end'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_start_date',
            field=partial_date.fields.PartialDateField(help_text='When was the document written? Supply at least a year.', verbose_name='Creation period start'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent_ref_number',
            field=models.ForeignKey(help_text='Reference number of the source', on_delete=django.db.models.deletion.PROTECT, to='main.refnumber', verbose_name='Reference Number'),
        ),
    ]
