# Generated by Django 3.2.3 on 2021-06-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210601_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='material',
            field=models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'Paper'), (2, 'Parchment'), (3, 'Papyrus')], help_text='Is the manuscript on paper, papyrus or parchment?', null=True, verbose_name='Writing material'),
        ),
    ]
