# Generated by Django 3.2.11 on 2022-01-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_api_auth_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_auth_key_expiration',
            field=models.DateField(default=None, null=True),
        ),
    ]
