# Generated by Django 3.2.11 on 2022-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_api_auth_key_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
