# Generated by Django 3.2.4 on 2021-06-30 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_document_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='different_editor_subscription',
            field=models.BooleanField(default=True, help_text='Do you want to be notified when your documents were edited by another user?', verbose_name='Subscription to owned documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_policy',
            field=models.IntegerField(choices=[(1, 'No notification E-Mails'), (2, 'Every time a subscribed document has changed.'), (3, 'Once a day, only if changes happened.'), (4, 'Once a week, only if changes happened.')], default=3, help_text='How often do you want to be notified about your subscribed documents?', verbose_name='Notification policy'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_orcid',
            field=models.CharField(default='', help_text='User id from https://orcid.org/', max_length=255, verbose_name='Orcid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mark_anonymous',
            field=models.BooleanField(default=False, help_text='If selected, your documents will be published anonymously by default. Can be changed on a document basis.', verbose_name='Mark anonymous by default'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.IntegerField(choices=[(1, 'Reference number'), (2, 'Document'), (3, 'User')])),
                ('object_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
