# Generated by Django 3.2.4 on 2021-07-15 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210630_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_notification_policy',
            field=models.IntegerField(choices=[(1, 'No notification E-Mails'), (2, 'Every time a message is sent.'), (3, 'Once a day, only if you received messages.')], default=2, help_text='How often do you want to be notified about messages you receive?', verbose_name='Message Notification policy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_policy',
            field=models.IntegerField(choices=[(1, 'No notification E-Mails'), (2, 'Every time a subscribed document has changed.'), (3, 'Once a day, only if changes happened.'), (4, 'Once a week, only if changes happened.')], default=3, help_text='How often do you want to be notified about your subscribed documents?', verbose_name='Subscription Notification policy'),
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('viewing_state', models.IntegerField()),
                ('receiving_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tc_msg_rec_user', to=settings.AUTH_USER_MODEL)),
                ('sending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tc_msg_send_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
