# Generated by Django 3.2.11 on 2022-02-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactmessage_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='answer_subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
