# Generated by Django 3.2.4 on 2021-07-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210715_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='viewing_state',
            field=models.IntegerField(default=0),
        ),
    ]
