# Generated by Django 3.2.11 on 2022-02-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactmessage_answer_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refnumber',
            name='ref_number_title',
            field=models.CharField(help_text='Title of the collection', max_length=150, verbose_name='Title'),
        ),
    ]
