# Generated by Django 3.2.11 on 2022-04-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_refnumber_ref_number_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Document Scribe', 'verbose_name_plural': 'Document Scribes'},
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='type_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='type_description_de',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='type_description_fr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='type_description_it',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_gnd',
            field=models.URLField(blank=True, help_text='Persistent URL to the GND entry of the scribe.', max_length=100, verbose_name='Link to GND entry'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(help_text='Name of the scribe of the original document.', max_length=150, verbose_name='Name of scribe'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Scribes of the source', to='main.Author', verbose_name='Scribes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='material',
            field=models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'Paper'), (2, 'Parchment'), (3, 'Papyrus'), (4, 'Metal'), (5, 'Textile'), (6, 'Stone'), (7, 'Wood')], help_text='Is the manuscript on paper, papyrus or parchment?', null=True, verbose_name='Writing material'),
        ),
        migrations.AlterField(
            model_name='document',
            name='paging_system',
            field=models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (0, 'No page numbering'), (1, 'Pagination'), (2, 'Foliated')], help_text='How are the pages numbered?', null=True, verbose_name='Pagination System'),
        ),
        migrations.AlterField(
            model_name='document',
            name='publish_user',
            field=models.BooleanField(default=False, help_text='Select this, if you want to publish this document anonymously', verbose_name='Publish anonymously'),
        ),
        migrations.AlterField(
            model_name='refnumber',
            name='holding_institution',
            field=models.ForeignKey(help_text='Institution which holds this reference number and document', on_delete=django.db.models.deletion.PROTECT, to='main.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='refnumber',
            name='ref_number_name',
            field=models.CharField(help_text='Reference number of the collection containing a document', max_length=100, verbose_name='Reference number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='message_notification_policy',
            field=models.IntegerField(choices=[(1, 'No notification Emails'), (2, 'Every time a message is sent.'), (3, 'Once a day, only if you received messages.')], default=2, help_text='How often do you want to be notified about messages you receive?', verbose_name='Message Notification policy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_policy',
            field=models.IntegerField(choices=[(1, 'No notification Emails'), (2, 'Every time a subscribed document has changed.'), (3, 'Once a day, only if changes happened.'), (4, 'Once a week, only if changes happened.')], default=3, help_text='How often do you want to be notified about your subscribed documents?', verbose_name='Subscription Notification policy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_orcid',
            field=models.CharField(blank=True, default='', help_text='User id from https://orcid.org/', max_length=255, verbose_name='Orcid'),
        ),
    ]
