# Generated by Django 3.2.4 on 2021-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_usermessage_sending_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='message_type',
            field=models.IntegerField(default=0),
        ),
    ]
