# Generated by Django 3.2.11 on 2022-06-06 17:22

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220429_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='document',
            name='comments',
            field=models.TextField(blank=True, help_text='Add editorial comments or remarks on the contents of the document', verbose_name='Editorial comments'),
        ),
        migrations.AlterField(
            model_name='document',
            name='commit_message',
            field=models.CharField(default='initial', help_text='A brief description of the applied changes', max_length=255, verbose_name='Changes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='ID of the first Version of this document. Is kept constant between versions of this document', verbose_name='Document UUID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='illuminated',
            field=models.BooleanField(blank=True, help_text='Does the source contain painted miniatures (illuminations)?', null=True, verbose_name='Illuminations'),
        ),
        migrations.AlterField(
            model_name='document',
            name='material',
            field=models.IntegerField(blank=True, choices=[(None, '(Unknown)'), (1, 'Paper'), (2, 'Parchment'), (3, 'Papyrus'), (4, 'Metal'), (5, 'Textile'), (6, 'Stone'), (7, 'Wood')], help_text='Which material is the Document written on?', null=True, verbose_name='Writing material'),
        ),
        migrations.AlterField(
            model_name='document',
            name='place_name',
            field=models.CharField(help_text='The City/Place where the source was created', max_length=150, verbose_name='Creation Location'),
        ),
        migrations.AlterField(
            model_name='document',
            name='transcription_text',
            field=ckeditor.fields.RichTextField(help_text='Formatted text of your transcript', verbose_name='Transcript'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='news_file',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='plain_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('de', 'German')], default='en', help_text='What is your preferred language?', max_length=20, verbose_name='Default User Interface Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='message_notification_policy',
            field=models.IntegerField(choices=[(1, 'No notification Emails'), (2, 'Every time a message is received.'), (3, 'Once a day, only if you received messages.')], default=2, help_text='How often do you want to be notified about messages you receive?', verbose_name='Message Notification policy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ui_language',
            field=models.CharField(choices=[('en-us', 'English'), ('de', 'German')], default='en', help_text='What is your preferred language?', max_length=20, verbose_name='Default User Interface Language'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_type',
            field=models.IntegerField(choices=[(1, 'Reference number'), (2, 'Document'), (3, 'User'), (4, 'Scribe'), (5, 'Institution'), (6, 'Source Type')]),
        ),
    ]
