# Generated by Django 3.2.11 on 2023-11-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220606_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ui_language',
            field=models.CharField(choices=[('en-us', 'English'), ('de', 'German')], default='en', help_text='What is your preferred language for email communication?', max_length=20, verbose_name='Communication Language'),
        ),
    ]
