# Generated by Django 3.2.4 on 2021-07-15 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_usermessage_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='message_type',
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('viewing_state', models.IntegerField(default=0)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersubscription')),
            ],
        ),
    ]
