# Generated by Django 3.2.4 on 2021-07-15 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210715_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='sending_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usersubscription'),
        ),
    ]
