# Generated by Django 3.2.11 on 2024-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20240926_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='ref_url_required',
            field=models.BooleanField(default=False),
        ),
    ]
