# Generated by Django 3.2.4 on 2021-07-26 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='sending_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
