# Generated by Django 3.2.4 on 2021-08-02 07:52

from django.db import migrations, models
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('main', '0019_contactmessage_sending_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution2',
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Authors, Copiers, Editors', null=True, to='main.Author', verbose_name='Source Participants'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_end_date',
            field=partial_date.fields.PartialDateField(blank=True, help_text="If the document was created over a time span, please indicate the end time. <br/>Valid fromats: YYYY ('1792'), MM.YYYY ('01.1980'), DD.MM.YYYY ('23.07.1643')", null=True, verbose_name='Creation period end'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_start_date',
            field=partial_date.fields.PartialDateField(help_text="When was the document written? Be as specific as possible. <br/>Valid fromats: YYYY ('1792'), MM.YYYY ('01.1980'), DD.MM.YYYY ('23.07.1643')", verbose_name='Creation period start'),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='Languages used in the source', null=True, to='languages_plus.Language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_type',
            field=models.IntegerField(choices=[(1, 'Reference number'), (2, 'Document'), (3, 'User'), (4, 'Author'), (5, 'Institution'), (6, 'Source Type')]),
        ),
    ]
