# Generated by Django 3.2.11 on 2025-04-18 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_utc_add',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 18, 4, 21, 621096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_utc_add',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 18, 4, 21, 621096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refnumber',
            name='ref_number_utc_add',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 18, 4, 21, 621096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 18, 4, 21, 637096, tzinfo=utc), verbose_name='Date joined'),
        ),
    ]
