# Generated by Django 3.0.4 on 2020-05-18 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttitle',
            options={'get_latest_by': 'document_utc_add', 'verbose_name': 'dokument', 'verbose_name_plural': 'dokumente'},
        ),
        migrations.AddField(
            model_name='documenttitle',
            name='document_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='ID des Urtexts; konstant zwischen aktuellen und alten Versionen einer Transkription', unique=True, verbose_name='urtext-id'),
        ),
        migrations.AddField(
            model_name='documenttitle',
            name='submitted_by',
            field=models.ForeignKey(default=2, editable=False, help_text='Benutzer*in, die/der diese Transkription eingereicht hat', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='eingereicht durch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='document_utc_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='einreichungsdatum'),
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='end_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')], help_text='MM', null=True, verbose_name='endmonat'),
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='start_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')], help_text='MM', null=True, verbose_name='startmonat'),
        ),
    ]
