# Generated by Django 3.0.4 on 2020-05-18 17:16

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_add_authoring_data'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='documenttitle',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='documenttitle',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='document_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, help_text='ID des Urtexts; konstant zwischen aktuellen und alten Versionen einer Transkription', verbose_name='urtext-id'),
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='document_slug',
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name='documenttitle',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('document_slug',), name='unique_active_slug'),
        ),
        migrations.AddConstraint(
            model_name='documenttitle',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('document_id',), name='unique_active_docid'),
        ),
    ]
