# Generated by Django 3.0.4 on 2020-05-31 14:08

from django.db import migrations, models


def set_null(apps, schema_editor):
    DocumentTitle = apps.get_model('transcripts', 'DocumentTitle')
    DocumentTitle.all_objects.update(illuminated=None, seal=None)


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0005_documenttitle_commit_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttitle',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='Autor*innen, Kopist*innen, Editor*innen', related_name='works', to='transcripts.Author', verbose_name='beteiligte Personen'),
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='illuminated',
            field=models.CharField(blank=True, null=True, choices=[('JA', 'Ja'), ('NEIN', 'Nein')], help_text='Ist die Quelle illuminiert?', max_length=4, verbose_name='illuminiert'),
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='seal',
            field=models.CharField(blank=True, null=True, choices=[('JA', 'Ja'), ('NEIN', 'Nein')], help_text='Sind Siegel erhalten?', max_length=4, verbose_name='siegel'),
        ),
        migrations.RunPython(set_null),
        migrations.AlterField(
            model_name='documenttitle',
            name='illuminated',
            field=models.BooleanField(help_text='Ist die Quelle illuminiert?', null=True, verbose_name='illuminiert'),
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='seal',
            field=models.BooleanField(help_text='Sind Siegel erhalten?', null=True, verbose_name='siegel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=True, help_text='Hat der User die E-Mailadresse bestätigt?', verbose_name='email bestätigt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Kann sich der User in den Admin-Bereich einloggen?', verbose_name='staff status'),
        ),
        migrations.AlterModelOptions(
            name='documenttitle',
            options={'default_manager_name': 'objects', 'get_latest_by': 'document_utc_add', 'verbose_name': 'dokument',
                     'verbose_name_plural': 'dokumente'},
        ),
        migrations.AlterModelManagers(
            name='documenttitle',
            managers=[
            ],
        ),
    ]
