# Generated by Django 3.0.4 on 2020-06-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0008_auto_20200602_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='vorname', max_length=150, verbose_name='vorname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='nachname', max_length=150, verbose_name='nachname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='place_name',
            field=models.CharField(help_text='Entstehungsort der Quelle', max_length=150, verbose_name='entstehungsort'),
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='source_type',
            field=models.ForeignKey(default=1, help_text='Archivalienart/Quellengattung', on_delete=django.db.models.deletion.PROTECT, to='transcripts.SourceType', verbose_name='archivalienart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenttitle',
            name='start_year',
            field=models.SmallIntegerField(default=1000, help_text='YYYY', verbose_name='startjahr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_type', to='transcripts.SourceType', verbose_name='übergeordnete Archivalienart'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='benutzername'),
        ),
    ]
