"""
Django settings for transcriptiones.ch project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from django.contrib import messages
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2!br_du&%2-^&zbygsfv#y)ekw3a&=kx$i$=vk2sfj45rv2z70'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Application definition

INSTALLED_APPS = [
    'main.apps.MainConfig',
    'django_static_fontawesome',
    'django_countries',
    'languages_plus',
    'countries_plus',
    'ckeditor',
    'django_tables2',
    'crispy_forms',
    'bsmodals',
    'django_filters',
    'bootstrap4',
    'easy_pdf',
    'rest_framework',
    'dal',              # Remove
    'dal_select2',      # Remove
    'widget_tweaks',
    'django_elasticsearch_dsl',
    'django_elasticsearch_dsl_drf',
    'django_bootstrap_breadcrumbs',
    'bootstrap_modal_forms',
    'cookielaw',
    'django_crontab',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'transcriptiones.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.user_notifications',
                'cookielaw.context_processors.cookielaw',
            ],
        },
    },
]

WSGI_APPLICATION = 'transcriptiones.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'transcriptiones',
        'USER': 'transcriptiones_user',
        'PASSWORD': 'transcriptiones',
        # 'PASSWORD': 's0uW@nn@KrrackTh1z?gudLöck',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Cron jobs
CRONJOBS = [
    ('* * * * *', 'main.cron.send_daily_notification_email'), # 7 o' clock every day
    ('1 0 * * 0', 'main.cron.send_weekly_notification_email')   # 7 o' clock every monday
    # ('0 * * * *', )
]

# Configuration for country selection
COUNTRIES_FIRST = ['CH', 'DE', 'FR', 'IT']
COUNTRIES_FIRST_REPEAT = True
COUNTRIES_FIRST_BREAK = _('--- (Select Country) ---')

# Configuration for Authentication

AUTH_USER_MODEL = 'main.User'
LOGIN_REDIRECT_URL = 'main:start'
LOGIN_URL = 'main:login'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_CODE = 'en-us'
LANGUAGES = (
    ('en-us', _('English')),
    ('de', _('German')),
    # ('fr', _('French')),
    # ('it', _('Italian')),
)

TIME_ZONE = 'Europe/Zurich'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Email configuration
# print emails to console for development purposes.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# PRODUCTION SETTINGS
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = False
# EMAIL_HOST = 'smtp.unibas.ch'
# EMAIL_PORT = 23
NO_REPLY_EMAIL = "no-reply@transcriptiones.ch"


# AUTO FIELD
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# CKEDITOR
# CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Transcriptiones',
        'extraPlugins': ','.join(
            [
                'autogrow',
                'linenumbers',
            ]
        ),
        'toolbar_Transcriptiones': [
            ['Format'],
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList'],
            ['Table', 'HorizontalRule'],
            ['SpecialChar'],
            ['RemoveFormat', 'Undo', 'Redo', 'Maximize']
        ],

        'toolbar_MyFull': [
            ['Styles', 'Format'],
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['SpellChecker'],
            ['Undo', 'Redo'],
            ['NumberedList', 'BulletedList'],
            ['Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['SpecialChar', 'Smiley', 'About'],
            ['RemoveFormat', 'Source'],
            ['Maximize']
        ],

        'width': 'auto',

        'specialChars': ['\u0363',  # combining latin small letter a
                         'E\u0363',
                         'e\u0363',
                         'I\u0363',
                         'i\u0363',
                         'O\u0363',
                         'o\u0363',
                         'U\u0363',
                         'u\u0363',
                         'V\u0363',
                         'v\u0363',
                         '\u0364',  # combining latin small letter e
                         'A\u0364',
                         'a\u0364',
                         'I\u0364',
                         'i\u0364',
                         'O\u0364',
                         'o\u0364',
                         'U\u0364',
                         'u\u0364',
                         'V\u0364',
                         'v\u0364',
                         '\u0365',  # combining latin small letter i
                         'A\u0365',
                         'a\u0365',
                         'E\u0365',
                         'e\u0365',
                         'O\u0365',
                         'o\u0365',
                         'U\u0365',
                         'u\u0365',
                         'V\u0365',
                         'v\u0365',
                         '\u0366',  # combining latin small letter o
                         'A\u0366',
                         'a\u0366',
                         'E\u0366',
                         'e\u0366',
                         'I\u0366',
                         'i\u0366',
                         'U\u0366',
                         'u\u0366',
                         'V\u0366',
                         'v\u0366',
                         '\u0367',  # combining latin small letter u
                         'A\u0367',
                         'a\u0367',
                         'E\u0367',
                         'e\u0367',
                         'I\u0367',
                         'i\u0367',
                         'O\u0367',
                         'o\u0367',
                         '\u036E',  # combining latin small letter v
                         'A\u036E',
                         'a\u036E',
                         'E\u036E',
                         'e\u036E',
                         'I\u036E',
                         'i\u036E',
                         'O\u036E',
                         'o\u036E',
                         '\u00D0',  # latin capital letter eth
                         '\u00F0',  # latin small letter eth
                         '\u00DE',  # latin capital letter thorn
                         '\u00FE',  # latin small letter thorn
                         '\u00C6',  # latin capital letter AE
                         '\u00E6',  # latin small letter ae
                         '\u00D8',  # latin capital letter O with stroke
                         '\u00F8',  # latin small letter O with stroke
                         ]
    }
}

MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }

CRISPY_TEMPLATE_PACK = 'bootstrap4'

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': 'localhost:9200'
    },
}