# Generated by Django 3.0.4 on 2020-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_add_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttitle',
            name='submitted_by_anonymous',
            field=models.BooleanField(default=False, help_text='Anwählen, um bei der Transkription keinen Benutzernamen anzuzeigen', verbose_name='Anonymer Beitrag'),
        ),
    ]
