# Generated by Django 3.0.4 on 2020-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0004_add_anonymity'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttitle',
            name='commit_message',
            field=models.CharField(default='initial', help_text='Knappe Beschreibung der Änderungen', max_length=255, verbose_name='Änderungen'),
        ),
    ]
