# Generated by Django 3.0.4 on 2020-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0006_boolean_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttitle',
            name='version_number',
            field=models.IntegerField(default=1, help_text='Versionsnummer', verbose_name='versionsnummer'),
        ),
    ]
