# Generated by Django 3.0.4 on 2020-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0007_documenttitle_version_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documenttitle',
            constraint=models.UniqueConstraint(fields=('document_id', 'version_number'), name='version_by_document'),
        ),
    ]
