# Generated by Django 3.0.4 on 2020-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=True, help_text='Hat der User die Emailadresse bestätigt?', verbose_name='email bestätigt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ist der User aktiv? False setzen, statt löschen.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Kann sich der User in den Admin-Bereich inloggen?', verbose_name='staff status'),
        ),
    ]
